config/routes.rb
Rails.application.routes.draw do
  resources :elearning do member do get :subscribers end end
  resources :students do member do get :subscribeds end end
  get  '/signup',  to: 'students#new'
  post '/signup',  to: 'students#create'
  post 'elearning/new', to: 'elearning#create' #new path for create
  patch 'elearning/:id/edit', to: 'elearning#update', as: "elearning_id_edit"
  put 'elearning/:id/edit', to: 'elearning#update', as: "elearning_id_update"
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  resources :subscriptions,       only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/elearning_controller.rb
class ElearningController < ApplicationController
    layout "elearning_show", only: :show
    layout "student", only: [:new, :create, :edit, :update]
    before_action :teacher_user, only: [:new, :create, :edit, :update, :destroy]
    before_action :correct_teacher, only: [:edit, :update, :destroy]
    def index
        @courses = Course.joins(:student).select('courses.course_id, courses.name, courses.category, courses.cover, courses.fee, students.student_id as sid, students.name as teacher_name, courses.created_at') 
        if params[:term]
            @courses1 = @courses.where('courses.name LIKE ?', "%#{params[:term]}%")
        else 
            @courses1 = @courses
        end
    end
    def show
        @course = Course.find(params[:id])
        @teacher = Student.find(@course[:student_id])
        @courses = Course.joins(:student).select('courses.course_id, courses.name, courses.category, courses.cover, courses.fee, students.student_id as sid, students.name as teacher_name').where(category: @course[:category]).take(2)
    end
    def new
        @course = current_user.courses.build
    end
    def create
        @course = current_user.courses.build(course_params)
        if @course.save
            flash[:success] = "Course created!"
            redirect_to elearning_index_path
        else
            render 'new'
        end
    end 
    def edit
        @course = Course.find(params[:id])
    end
    def update
        @course = Course.find(params[:id])
        if @course.update_attributes(course_params)
            # Handle a successful update.
            flash.now[:success] = "Profile updated"
            redirect_to elearning_index_path
        else
            render 'edit'
        end
    end
    def destroy
        @course = Course.find(params[:id])
        @course.remove_cover!
        @course.save!
        @course.destroy
        #flash[:success] = "Course deleted"
        redirect_to elearning_index_path
    end
    private
      #confirm teacher
      def teacher_user
        logged_in_user
        if logged_in?
            redirect_to elearning_index_path unless current_user.teacher?
        end
      end
      def correct_teacher
        @course = Course.find(params[:id])
        unless current_user.student_id == @course.student_id
            #flash[:danger] = "Not the right user"
            redirect_to elearning_index_path
        end
      end
      def course_params
        params.require(:course).permit(:name, :description, :fee, :aim, :category, :requirement, :cover, :remove_cover, :term)
      end
end

app/helpers/elearning_helper.rb
module ElearningHelper
end

app/views/elearning/edit.html.erb
<% provide(:title, 'Edit Course') %>
<h1>Edit Course</h1>

<div class="row">
</div>
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @course, url: elearning_id_update_path, local: true do |f|  %> 
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :aim, "The aim of the course" %>
      <%= f.text_area :aim %>

      <%= f.label :category %>
      <br />
      <%= f.label :category, "Math" %>
      <%= f.radio_button :category, "Math" %>
      <%= f.label :category, "Literature" %>
      <%= f.radio_button :category, "Literature" %>
      <%= f.label :category, "Linguistics" %>
      <%= f.radio_button :category, "Linguistics" %>

      <%= f.label :requirement %>
      <%= f.text_area :requirement %>

      <%= f.label :fee %>
      <%= f.number_field :fee %>

      <%= f.label :cover %>
      <%= f.file_field :cover %>
      <% if f.object.cover? %>
      <%= image_tag f.object.cover.thumb.url %>
      <%= f.label :remove_cover %>
      <%= f.check_box :remove_cover %> 
      <% end %>

      <%= f.submit "Update Course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/elearning/index.html.erb
<div class="page-header-overlay">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <header class="entry-header">
                                <h1>Online learning system</h1>
                            </header><!-- .entry-header -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .page-header-overlay -->
    </div><!-- .page-header -->
<div class="container">
        <div class="row">
            <div class="col-12">
                <div class="breadcrumbs">
                    <ul class="flex flex-wrap align-items-center p-0 m-0">
                        <li><%=link_to "Home", elearning_index_path %></li>
                        <li><%=link_to "Create New", new_elearning_path %></li>
                    </ul>
                </div><!-- .breadcrumbs -->
            </div><!-- .col -->
        </div><!-- .row -->
        <div class="row">
            <div class="col-12 col-lg-8">
                <div class="featured-courses courses-wrap">
                    <div class="row mx-m-25">
                    
                    <% @courses1.each do |course| %>
                        <div class="col-12 col-md-6 px-25">
                            <div class="course-content">
                                <figure class="course-thumbnail">
                                        <% if course.cover? %>
                                        <%= image_tag course.cover.thumb.url %>
                                        <% end%>
                                </figure><!-- .course-thumbnail -->

                                <div class="course-content-wrap">
                                    <header class="entry-header">
                                        <h2 class="entry-title"><%= link_to "#{course.name}", elearning_path(course.course_id) %></h2>

                                        <div class="entry-meta flex flex-wrap align-items-center">
                                            <div class="course-author"><%= link_to "#{course.teacher_name}", student_path(course[:sid]) %></div>

                                    </header><!-- .entry-header -->

                                    <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                        <div class="course-cost">
                                            <%= course.fee %>$
                                        </div><!-- .course-cost -->

            
                                    </footer><!-- .entry-footer -->
                                </div><!-- .course-content-wrap -->
                            </div><!-- .course-content -->
                        </div><!-- .col -->
                        <% end %>
                        </div><!-- .row -->
                        </div><!-- .featured-courses -->
                        
                        </div><!-- .col -->
                <div class="col-12 col-lg-4">
                <div class="sidebar">
                    <div class="search-widget">
                        <form class="flex flex-wrap align-items-center">
                            <input type="search" placeholder="Search...">
                            <button type="submit" class="flex justify-content-center align-items-center"><i class="fa fa-search"></i></button>
                        </form><!-- .flex -->
                    </div><!-- .search-widget -->

                    <div class="cat-links">
                        <h2>Categories</h2>

                        <ul class="p-0 m-0">
                            <li><a href="#">Math</a></li>
                            <li><a href="#">Literature</a></li>
                            <li><a href="#">Linguistics</a></li>
                        </ul>
                    </div><!-- .cat-links -->

                    <div class="latest-courses">
                        <h2>Latest Courses</h2>

                        <ul class="p-0 m-0">
                        <% @courses.sort_by{|t| - t.created_at.to_i}.first(4).each do |course| %>
                            <li class="flex flex-wrap justify-content-between align-items-center">
                               <% if course.cover? %>
                                <%= image_tag course.cover.small_thumb.url %>
                                <% end%>
                                <div class="content-wrap">
                                    <h3><%= link_to "#{course.name}", elearning_path(course.course_id) %></h3>

                                    <div class="course-cost"><%= course.fee %>$</div>
                                </div><!-- .content-wrap -->
                            </li>

                            <% end %>
                        </ul>
                    </div><!-- .latest-courses -->
                </div><!-- .sidebar -->
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->

app/views/elearning/new.html.erb
<% provide(:title, 'New Course') %>
<h1>New Course</h1>

<div class="row">
</div>
  <div class="col-md-6 col-md-offset-3">
    <%= form_with model: @course, url:elearning_new_path, local: true do |f|  %> 
      <%= render 'shared/error_messages', object: f.object %>
      <%= f.label :name %>
      <%= f.text_field :name %>

      <%= f.label :description %>
      <%= f.text_area :description %>

      <%= f.label :aim, "The aim of the course" %>
      <%= f.text_area :aim %>

      <%= f.label :category %>
      <br />
      <%= f.label :category, "Math" %>
      <%= f.radio_button :category, "Math" %>
      <%= f.label :category, "Literature" %>
      <%= f.radio_button :category, "Literature" %>
      <%= f.label :category, "Linguistics" %>
      <%= f.radio_button :category, "Linguistics" %>

      <%= f.label :requirement %>
      <%= f.text_area :requirement %>

      <%= f.label :fee %>
      <%= f.number_field :fee %>

      <%= f.label :cover %>
      <%= f.file_field :cover %>

      <%= f.submit "Create Course", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/elearning/show.html.erb
<div class="page-header-overlay">
            <div class="container">
                <div class="row">
                    <div class="col-12">
                        <header class="entry-header">
                                <h1><%= @course[:name] %></h1>
                            </header><!-- .entry-header -->
                    </div><!-- .col -->
                </div><!-- .row -->
            </div><!-- .container -->
        </div><!-- .page-header-overlay -->
    </div><!-- .page-header -->
    <div class="container">
        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-10">
                <div class="featured-image">
                <% if @course.cover? %>
                <%= image_tag @course.cover.url %>
                <% end%>
                    <div class="course-cost"><%= @course[:fee] %>$</div>
                </div>
            </div><!-- .col -->
        </div><!-- .row -->

        <div class="row">
            <div class="col-12 offset-lg-1 col-lg-1">
                <div class="post-share">
                    <h3>share</h3>

                    <ul class="flex flex-wrap align-items-center p-0 m-0">
                        <li><a href="#"><i class="fa fa-facebook"></i></a></li>
                        <li><a href="#"><i class="fa fa-twitter"></i></a></li>
                        <li><a href="#"><i class="fa fa-google-plus"></i></a></li>
                        <li><a href="#"><i class="fa fa-instagram"></i></a></li>
                        <li><a href="#"><i class="fa fa-thumb-tack"></i></a></li>
                    </ul>
                </div><!-- .post-share -->
            </div><!-- .col -->
            <div class="col-12 col-lg-8">
                <div class="single-course-wrap">
                    <div class="course-info flex flex-wrap align-items-center">
                        <div class="course-author flex flex-wrap align-items-center mt-3">	

                            <div class="author-wrap">
                                <label class="m-0">Teacher</label>
                                <div class="author-name"><%=link_to "#{@teacher[:name]}", @teacher %></div>
                            </div><!-- .author-wrap -->
                        </div><!-- .course-author -->
                        <div class="course-cats mt-3"> 
                            <label class="m-0">Categories</label>
                            <div class="author-name"><a href="#"><%= @course[:category] %>
							</a></div>
                        </div><!-- .course-cats -->

                        <div class="course-students mt-3">
                            <label class="m-0">Student</label>
                            <div class="author-name"><%= @course.subscribers.count %></div>
                        </div><!-- .course-students -->
                        <% if logged_in? %>
                          <% if current_user[:student_id] == @course[:student_id] %>
                        <div class="course-students mt-3">
                            <label class="m-0">Edit</label>
                            <div class="author-name"><%=link_to "Edit", edit_elearning_path %></div>
                        </div><!-- .course-students -->
                        <div class="course-students mt-3">
                            <label class="m-0">Delete</label>
                            <div class="author-name"><%=link_to "Delete", elearning_url, method: :delete,
                                  data: { confirm: "You sure?" } %> </div>
                        </div><!-- .course-students -->
                          <% else %>
                            <% if current_user.subscribed?(@course) %>
                            <%= form_for(current_user.subscriptions.find_by(subscribed_id: @course.course_id), html: { method: :delete }, data: { confirm: "You sure?" }) do |f| %>
                            <div class="buy-course mt-3"><%= f.submit "UNFOLLOW", class: "btn" %></div>
                            <% end %>
                            <% else %>
                                <% if current_user.budget > @course.fee %>
                                <%= form_for(current_user.subscriptions.build, data: { confirm: "You sure?" }) do |f| %>
                                <div><%= hidden_field_tag :subscribed_id, @course.course_id %></div>
                                <div class="buy-course mt-3"><%= f.submit "BUY NOW", class: "btn" %></div><!-- .buy-course -->
                                    <% end %>
                                <% else %>
                                <div class="author-name">Not enough budget</div>
                                <%end%>
                            <% end %>
                          <% end %>
                        <% else %>
                            <div class="author-name"><%=link_to "Log in to buy course", login_path %></div>
                        <% end %>


                    </div><!-- .course-info -->

                    <div class="single-course-cont-section">
                        <h2>What Will I Learn? </h2>

                        <ul class="p-0 m-0 green-ticked">
						<li><%= @course[:aim] %></li>
                        </ul>

                        <h2>Requirements</h2>

                        <ul class="p-0 m-0 black-doted">
						<li><%= @course[:requirement] %></li>
                        </ul>
						
                        <h2>Description</h2>

                        <p><%= @course[:description] %></p>


                    <div class="related-courses">
                        <header class="entry-heading flex flex-wrap justify-content-between align-items-center">
                            <h2 class="entry-title">Related Courses</h2>

                            <%= link_to "View all", elearning_index_path %>
                        </header><!-- .entry-heading -->
                        
                        <div class="row mx-m-25">
                           <% @courses.each do |course| %>
                           <% if course.course_id != @course.course_id %>
                            <div class="col-12 col-lg-6 px-25">
                                <div class="course-content">
                                    <figure class="course-thumbnail">
                                        <% if course.cover? %>
                                        <%= image_tag course.cover.thumb.url %>
                                        <% end%>
                                    </figure><!-- .course-thumbnail -->

                                    <div class="course-content-wrap">
                                        <header class="entry-header">
                                            <h2 class="entry-title"><%= link_to "#{course.name}", elearning_path(course.course_id) %></h2>

                                            <div class="entry-meta flex flex-wrap align-items-center">
                                                <div class="course-author"><%= link_to "#{course.teacher_name}", student_path(course.sid) %></div>

                                            
                                        </header><!-- .entry-header -->

                                        <footer class="entry-footer flex flex-wrap justify-content-between align-items-center">
                                            <div class="course-cost">
                                                <%= course.fee %>$
                                            </div><!-- .course-cost -->
                                        </footer><!-- .entry-footer -->
                                    </div><!-- .course-content-wrap -->
                                </div><!-- .course-content -->
                            </div><!-- .col -->
                            <% end %>
                            <% end %>
                        </div><!-- .row -->
                    </div><!-- .related-course -->
                </div><!-- .single-course-wrap -->
            </div><!-- .col -->
        </div><!-- .row -->
    </div><!-- .container -->